//
//  Data.swift
//  0065701_HW2
//
//  Created by Shaun Ku on 2019/10/6.
//  Copyright © 2019 Shaun Ku. All rights reserved.
//

import Foundation
let movies =
[
    Movie(name:"Star Wars: The Rise of Skywalker", pic_to_show:"Starwars", mainactor: "Daisy Ridley, Adam Driver", detail:"A year after the events of The Last Jedi, the remnants of the Resistance face the First Order once again—while reckoning with the past and their own inner turmoil. Meanwhile, the ancient conflict between the Jedi and the Sith reaches its climax, altogether bringing the Skywalker saga to a definitive end.", scenepicture:["Starwars0", "Starwars1", "Starwars2"]),
    Movie(name:"Joker", pic_to_show:"Joker", mainactor: "Joaquin Phoenix", detail:"In Gotham City, mentally-troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego:“The Joker”.", scenepicture:["Joker0", "Joker1", "Joker2"]),
    Movie(name:"Kingsman: The Secret Service", pic_to_show:"Kingsman", mainactor: "Colin Firth, Taron Egerton, Samuel L. Jackson", detail:"A spy organization recruits an unrefined, but promising street kid into the agency's ultra-competitive training program, just as a global threat emerges from a twisted tech genius.", scenepicture:["Kingsman0", "Kingsman1", "Kingsman2"]),
    Movie(name:"Avengers: Endgame", pic_to_show:"Avengers", mainactor: "Robert Downey Jr., Chris Evans, Mark Ruffalo", detail:"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", scenepicture:["Avengers0", "Avengers1", "Avengers2"]),
    Movie(name:"Spider-Man: Far from Home", pic_to_show:"Spiderman", mainactor: "Robert Downey Jr., Chris Evans, Mark Ruffalo", detail:"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", scenepicture:["Spiderman0", "Spiderman1", "Spiderman2"]),
    Movie(name:"The Golden Compass", pic_to_show:"Goldencompass", mainactor: "Nicole Kidman, Daniel Craig, Dakota Blue Richards", detail:"In a parallel universe, young Lyra Belacqua journeys to the far North to save her best friend and other kidnapped children from terrible experiments by a mysterious organization.", scenepicture:["Goldencompass0", "Goldencompass1", "Goldencompass2"]),
    Movie(name:"The Maze Runner", pic_to_show:"Mazerunner", mainactor: "Dylan O'Brien, Kaya Scodelario, Will Poulter", detail:"Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.", scenepicture:["Mazerunner0", "Mazerunner1", "Mazerunner2"]),
    Movie(name:"Inception", pic_to_show:"Inception", mainactor: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page", detail:"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", scenepicture:["Inception0", "Inception1", "Inception2"]),
    Movie(name:"Black Panther", pic_to_show:"Blackpanther", mainactor: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o", detail:"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.", scenepicture:["Blackpanther0", "Blackpanther1", "Blackpanther2"]),
    Movie(name:"Mission: Impossible - Fallout", pic_to_show:"Missionimpossible", mainactor: "Tom Cruise, Henry Cavill, Ving Rhames", detail:"Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.", scenepicture:["Missionimpossible0", "Missionimpossible1", "Missionimpossible2"]),
    Movie(name:"Chalard games goeng", pic_to_show:"Badgenius", mainactor: "Chutimon Chuengcharoensukying, Eisaya Hosuwan, Teeradon Supapunpinyo", detail:"Lynn, a genius high school student who makes money by cheating tests, receives a new task that leads her to set foot on Sydney, Australia. In order to complete the millions-Baht task, Lynn and her classmates have to finish the international STIC(SAT) exam and deliver the answers back to her friends in Thailand before the exam takes place once again in her home country.", scenepicture:["Badgenius0", "Badgenius1", "Badgenius2"]),
    Movie(name:"Ratatouille", pic_to_show:"Ratatouille", mainactor: "Brad Garrett, Lou Romano, Patton Oswalt", detail:"A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.", scenepicture:["Ratatouille0", "Ratatouille1", "Ratatouille2"])
    
]

let actors =
[
    Actor(name:"Tom Cruise", pic_to_show:["TomCruise0", "TomCruise1", "TomCruise2"], gender:"Male", masterpiece:"Mission Impossible", intro:"Thomas Cruise (born Thomas Cruise Mapother IV; July 3, 1962) is an American actor and film producer. He has received several accolades for his work, including three Golden Globe Awards and nominations for three Academy Awards. Cruise is one of the best-paid actors in the world, and his films have grossed over $4 billion in North America and over $10.1 billion worldwide, making him one of the highest-grossing box-office stars of all time."),
    Actor(name:"Robert Downey Jr.", pic_to_show:["RobertDowney0", "RobertDowney1", "RobertDowney2"], gender:"Male", masterpiece:"Iron Man", intro:"Robert John Downey Jr. (born April 4, 1965) is an American actor, producer, comedian and singer. His career has been characterized by critical and popular notoriety in his youth, followed by a period of substance abuse and legal troubles, before a resumption of critical repute and resurgence of commercial success in middle age. In 2008, Downey was named by Time magazine among the 100 most influential people in the world, and from 2013 to 2015, he was listed by Forbes as Hollywood's single highest-paid actor. His films have grossed over $5.8 billion in North America and over $14.4 billion worldwide, making him the second-highest-grossing box-office actor to date both domestically and worldwide."),
    Actor(name:"Will Smith", pic_to_show:["WillSmith0", "WillSmith1", "WillSmith2"], gender:"Male", masterpiece:"Men in Black", intro:"Willard Carroll Smith Jr. (born September 25, 1968) is an American actor, rapper and media personality. In April 2007, Newsweek called him “the most powerful actor in Hollywood”. Smith has been nominated for five Golden Globe Awards and two Academy Awards, and has won four Grammy Awards."),
    Actor(name:"Morgan Freeman", pic_to_show:["MorganFreeman0", "MorganFreeman1", "MorganFreeman2"], gender:"Male", masterpiece:"Se7en", intro:"Morgan Freeman (born June 1, 1937) is an American actor, film director, and film narrator. Freeman won an Academy Award in 2005 for Best Supporting Actor with Million Dollar Baby (2004), and he has received Oscar nominations for his performances in Street Smart (1987), Driving Miss Daisy (1989), The Shawshank Redemption (1994), and Invictus (2009). He has also won a Golden Globe Award and a Screen Actors Guild Award."),
    Actor(name:"Robert Duvall", pic_to_show:["RobertDuvall0", "RobertDuvall1", "RobertDuvall2"], gender:"Male", masterpiece:"The Apostle", intro:"Robert Selden Duvall (born January 5, 1931)[5] is an American actor and filmmaker whose career spans more than six decades. He has been nominated for seven Academy Awards (winning for his performance in Tender Mercies) and seven Golden Globe Awards (winning four), and has won a BAFTA, a Screen Actors Guild Award, and an Emmy Award. He received the National Medal of Arts in 2005. Duvall has starred in numerous films and television series, including To Kill a Mockingbird (1962), The Twilight Zone (1963), The Outer Limits (1964), Bullitt (1968), True Grit (1969), MASH (1970), THX 1138 (1971), Joe Kidd (1972), The Godfather (1972), The Godfather Part II (1974), The Conversation (1974), Network (1976), Apocalypse Now (1979), The Great Santini (1979), The Natural (1984), Lonesome Dove (1989), The Handmaid's Tale (1990), Days of Thunder (1990), Rambling Rose (1991), and Falling Down (1993)"),
    Actor(name:"Leonardo DiCaprio", pic_to_show:["LeonardoDiCaprio0", "LeonardoDiCaprio1", "LeonardoDiCaprio2"], gender:"Male", masterpiece:"Inception", intro:"Leonardo Wilhelm DiCaprio (born November 11, 1974) is an American actor, film producer, and environmentalist. He is known for starring in biopics and period films, and for playing unconventional roles. His films have earned $7.2 billion worldwide, and he was one of the world's highest-paid actors for eight years. His accolades include an Academy Award and three Golden Globe Awards."),
    Actor(name:"Johnny Depp", pic_to_show:["JohnnyDepp0", "JohnnyDepp1", "JohnnyDepp2"], gender:"Male", masterpiece:"Sweeney Todd: The Demon Barber of Fleet Street", intro:"John Christopher Depp II (born June 9, 1963) is an American actor, producer, and musician. He has been nominated for 10 Golden Globe Awards, winning one for Best Actor for his performance of the title role in Sweeney Todd: The Demon Barber of Fleet Street (2008) and has been nominated for three Academy Awards for Best Actor, among other accolades. He is regarded as one of the world's biggest film stars.")
]

let actresses =
[
    Actor(name:"Jennifer Lawrence", pic_to_show:["JenniferLawrence0", "JenniferLawrence1", "JenniferLawrence2"], gender:"Female", masterpiece:"The Hunger Games", intro:"Jennifer Shrader Lawrence (born August 15, 1990) is an American actress. The films she has acted in have grossed over $6 billion worldwide, and she was the highest-paid actress in the world in 2015 and 2016. Lawrence appeared in Time's 100 most influential people in the world list in 2013 and in the Forbes Celebrity 100 list in 2014 and 2016."),
    Actor(name:"Krysten Ritter", pic_to_show:["KrystenRitter0", "KrystenRitter1", "KrystenRitter2"], gender:"Female", masterpiece:"Jessica Jones", intro:"Krysten Alyce Ritter (born December 16, 1981) is an American actress, musician, author, and model. She is known for starring as the superhero Jessica Jones on the Netflix drama series Jessica Jones (2015–2019) and the miniseries The Defenders (2017). She also appeared as Jane Margolis on the AMC drama series Breaking Bad (2009–2010) and Chloe on the ABC comedy series Don't Trust the B---- in Apartment 23 (2012–2013)."),
    Actor(name:"Emma Watson", pic_to_show:["EmmaWatson0", "EmmaWatson1", "EmmaWatson2"], gender:"Female", masterpiece:"The Perks of Being a Wallflower", intro:"Emma Charlotte Duerre Watson (born 15 April 1990) is an English actress, model and activist. Born in Paris and brought up in Oxfordshire, Watson attended the Dragon School and trained as an actress at the Oxford branch of Stagecoach Theatre Arts. As a child artist, she rose to prominence after landing her first professional acting role as Hermione Granger in the Harry Potter film series, having acted only in school plays previously."),
    Actor(name:"Jamie Chung", pic_to_show:["JamieChung0", "JamieChung1", "JamieChung2"], gender:"Female", masterpiece:"Big Hero 6", intro:"Jamie Jilynn Chung (born April 10, 1983) is an American actress, and former reality television personality. She first gained fame in 2004 as a cast member on the MTV reality series The Real World: San Diego and subsequently through her appearances on its spin-off show, Real World/Road Rules Challenge: The Inferno II. She is regarded by many as the Real World alumna with the most successful media career."),
    Actor(name:"Megan Fox", pic_to_show:["MeganFox0", "MeganFox1", "MeganFox2"], gender:"Female", masterpiece:"Transformers", intro:"Megan Denise Fox (born May 16, 1986) is an American actress and model. She began her acting career in 2001, with several minor television and film roles, and played a regular role on the Hope & Faith television sitcom. In 2004, she made her film debut with a role in the teen comedy Confessions of a Teenage Drama Queen. In 2007, she co-starred as Mikaela Banes, the love interest of Shia LaBeouf's character, in the blockbuster action film Transformers, which became her breakout role. Fox reprised her role in the 2009 sequel, Transformers: Revenge of the Fallen. Later in 2009, she starred in the black comedy horror film Jennifer's Body. In 2014, Fox starred as April O'Neil in Teenage Mutant Ninja Turtles, and reprised the role in Teenage Mutant Ninja Turtles: Out of the Shadows (2016)."),
    Actor(name:"Jordana Brewster", pic_to_show:["JordanaBrewster0", "JordanaBrewster1", "JordanaBrewster2", "JordanaBrewster3", "JordanaBrewster4", "JordanaBrewster5", "JordanaBrewster6"], gender:"Female", masterpiece:"The Texas Chainsaw Massacre: The Beginning", intro:"Jordana Brewster (born April 26, 1980) is a Panamanian-American actress and model. She made her acting debut in an episode of All My Children in 1995 and next took on the recurring role as Nikki Munson in As the World Turns, garnering a nomination for Outstanding Teen Performer at the 1997 Soap Opera Digest Award. Her first role in a feature film was in Robert Rodriguez's horror science fiction The Faculty (1998)."),
    Actor(name:"Lily Collins", pic_to_show:["LilyCollins0", "LilyCollins1", "LilyCollins2"], gender:"Female", masterpiece:"The Mortal Instruments: City of Bones", intro:"Lily Jane Collins (born 18 March 1989) is an English-American actress, model, and writer.[1] The daughter of English musician Phil Collins and American Jill Tavelman, she was born in Surrey and moved to Los Angeles as a child. Her first screen role was at the age of two in the BBC series Growing Pains. She went on to study broadcast journalism at the University of Southern California, and as a teenager, wrote for Seventeen magazine, Teen Vogue, and The Los Angeles Times. She was named International Model of the Year by Spain's Glamour magazine after being selected by Chanel to wear one of their dresses at the Hotel de Crillon in 2007.")
]

